;;; Directory Local Variables            -*- no-byte-compile: t -*-
;;; For more information see (info "(emacs) Directory Variables")

((nil . ((require-final-newline . t)
	 (show-trailing-whitespace . t)))
 (c-mode . ((indent-tabs-mode . t)
	    (c-basic-offset . 2)
	    (tab-width . 8)
	    (c-default-style . "gnu")
	    (fill-column . 80)))
 (c-ts-mode . ((indent-tabs-mode . t)
	       (c-basic-offset . 2)
	       (tab-width . 8)
	       (c-default-style . "gnu")
	       (fill-column . 80)))
 (emacs-lisp-mode . ((mode . aggressive-indent))))
