;;; Directory Local Variables            -*- no-byte-compile: t -*-
;;; For more information see (info "(emacs) Directory Variables")

((nil . ((mode . envrc)
	 (require-final-newline . t)
	 (show-trailing-whitespace . t)
	 (eval . (defun reader-dev-generate-autoloads nil
		   "Create autoload for reader."
		   (interactive)
		   (loaddefs-generate (project-root (project-current))
				      "emacs-reader-autoloads.el")))))
 (c-mode . ((eval . (eglot-ensure))
	    (before-save-hook . (eglot-format-buffer))
	    (indent-tabs-mode . t)
	    (c-basic-offset . 2)
	    (tab-width . 8)
	    (c-default-style . "gnu")
	    (fill-column . 80)))
 (c-ts-mode . ((eval . (eglot-ensure))
	       (before-save-hook . (eglot-format-buffer))
	       (indent-tabs-mode . t)
	       (c-basic-offset . 2)
	       (tab-width . 8)
	       (c-default-style . "gnu")
	       (fill-column . 80)))
 (emacs-lisp-mode . ((after-save-hook . reader-dev-generate-autoloads)
		     (mode . aggressive-indent)))
 (scheme-mode . ((mode . aggressive-indent))))
