#+TITLE: The GNU Emacs Reader
#+OPTIONS: toc:nil

An all-in-one ebook reader for GNU Emacs, supporting all the major ebook formats. This package intends to take from =pdf-tools=, =nov.el=, and =doc-view= and make them better. And as such, it is effectively a drop-in replacement for them

* Supported Formats
The Emacs Reader (following MuPDF) renders all the formats below in SVGs (Scalable Vector Graphics):

** E-Book Formats
+ PDF
+ EPUB
+ MOBI
+ FB2
+ XPS/OpenXPS
+ CBZ

** Office Document Formats
These formats below aren’t really for e-book reading, and as such while they are supported by MuPDF and can be opened fine, it’s just not going to be that good of an experience. It should only be used for quickly checking the textual contents of the document, and certainly cannot be edited inside Emacs.

*** Open Document Formats (LibreOffice)
+ ODT
+ ODS
+ ODP
+ ODG

*** Proprietary Micro$oft Formats
Using these formats is heavily discouraged, since you’re using GNU software, you should /always/ prefer the above formats from LibreOffice. But since MuPDF does come with some very minimal support for these proprietary formats as well, they can also be viewed:

+ DOCX
+ PPTX
+ XLSX

* Dependencies
Technically the only thing this package depends on is =mupdf=, but for various reasons, the way it is packaged in most distributions (at least GNU Guix and Arch) is that it has a conflict with on of its own dependencies, effectively making the package unusable. So for now, =mupdf= is provided as a submodule in the repository until I can maybe talk to package maintainers of =mupdf= and see if things can be resolved.

So, since you’d be building =mupdf= from source to produce the shared object =libmupdf.so= which the package relies on, you’d need to have the depencies that =mupdf= has, check them from [[https://mupdf.readthedocs.io/en/1.25.0/quick-start-guide.html#get-the-mupdf-source-code][here]] and make sure you have them installed. But most of them are actually bundled with =mupdf= itself.

* Installation
For now, until the package has been published to GNU ELPA, the only way to install and use it is manual. Follow the following steps:

1. Do a recursive clone of the repository:
   #+begin_src sh
  git clone --recursive https://codeberg.org/divyaranjan/emacs-reader.git
   #+end_src
   Note: This will take a *long* time, since it’s getting =mupdf= and /all/ of its dependencies.

2. Add module directory to Emacs’ =load-path=, do the following in your Emacs session:
   #+begin_src emacs-lisp
     (add-to-list 'load-path "/path/to/package/")
     (add-to-list 'load-path "/path/to/package/module/")
   #+end_src
   Note that at the end there should be =module/= in the second one.

3. Install dependencies as described above.

4. Simply do =make= and then in your Emacs do =(require 'reader)=.

5. In Emacs do =M-x open-doc= or just =C-x C-f= and open a file of the aforementioned supported formats.

* Key Bindings
- =n= or =j= for going to next page
- =p= or =k= for going to previous page
- =Q= for closing the Emacs Reader buffer.
- =M-<= and =gg= for going to the first page.
- =M->= and =G= for going to the last page.
- =M-g g= or =g n= for going to a particular page.
- === and =-= for zooming in and out of the current page.
